import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {StoreProvider} from "@repo/ui/index";
import { GqlProvider } from "@repo/ui/index";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <GqlProvider>
     <StoreProvider>
        <body className={`${inter.className}`}>{children}</body>


      </StoreProvider>

     </GqlProvider>
    </html>
  );
}
